// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RzeczyDoOddaniaV2.Data;

#nullable disable

namespace RzeczyDoOddaniaV2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220611133430_Dodani_zainteresowani")]
    partial class Dodani_zainteresowani
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Kod_Pocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_domu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfertaId")
                        .IsUnique();

                    b.ToTable("Adresy");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NazwaKategorii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NazwaKategorii = "Motoryzacja"
                        },
                        new
                        {
                            Id = 2,
                            NazwaKategorii = "Dom i ogród"
                        },
                        new
                        {
                            Id = 3,
                            NazwaKategorii = "Elektronika"
                        },
                        new
                        {
                            Id = 4,
                            NazwaKategorii = "Odzież"
                        },
                        new
                        {
                            Id = 5,
                            NazwaKategorii = "Rolnictwo"
                        },
                        new
                        {
                            Id = 6,
                            NazwaKategorii = "Jedzenie"
                        },
                        new
                        {
                            Id = 7,
                            NazwaKategorii = "Zwierzęta"
                        },
                        new
                        {
                            Id = 8,
                            NazwaKategorii = "Sport"
                        },
                        new
                        {
                            Id = 9,
                            NazwaKategorii = "Dla dzieci"
                        });
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Komentarz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("komentarz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Komentarze");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Ocena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ocena")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Oceny");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataWygasniecia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kupiec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wlasciciel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Oferty");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.OfertaKategoria", b =>
                {
                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.HasKey("OfertaId", "KategoriaId");

                    b.HasIndex("KategoriaId");

                    b.ToTable("OfertyKategorie");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Zainteresowany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nazwa_Zainteresowanego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfertaId");

                    b.ToTable("Zainteresowani");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Zdjecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<string>("ZdjeciePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfertaId")
                        .IsUnique();

                    b.ToTable("Zdjecia");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Adres", b =>
                {
                    b.HasOne("RzeczyDoOddaniaV2.Models.Oferta", "Oferta")
                        .WithOne("Adres")
                        .HasForeignKey("RzeczyDoOddaniaV2.Models.Adres", "OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.OfertaKategoria", b =>
                {
                    b.HasOne("RzeczyDoOddaniaV2.Models.Kategoria", "Kategorie")
                        .WithMany("OfertyKategorie")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RzeczyDoOddaniaV2.Models.Oferta", "Oferty")
                        .WithMany("OfertyKategorie")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");

                    b.Navigation("Oferty");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Zainteresowany", b =>
                {
                    b.HasOne("RzeczyDoOddaniaV2.Models.Oferta", "Oferta")
                        .WithMany()
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Zdjecie", b =>
                {
                    b.HasOne("RzeczyDoOddaniaV2.Models.Oferta", "Oferta")
                        .WithOne("Zdjecie")
                        .HasForeignKey("RzeczyDoOddaniaV2.Models.Zdjecie", "OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Kategoria", b =>
                {
                    b.Navigation("OfertyKategorie");
                });

            modelBuilder.Entity("RzeczyDoOddaniaV2.Models.Oferta", b =>
                {
                    b.Navigation("Adres");

                    b.Navigation("OfertyKategorie");

                    b.Navigation("Zdjecie")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
